### ISSUE TITLE
Can we place our own finetuned model in app.py

### ISSUE THREAD

**Issue by honeybansal9** [deep-diver/LLM-Pref-Mark-UI#1]
Hi Team,

Can we place our own finetuned model in app.py?
If yes, then can you please guide me

**Comment by honeybansal9** [comment]
I have tried changing the model param and replace it with the the finetuned model.
The below error is coming

AttributeError: 'str' object has no attribute 'generate' in model.generate line no 32 in app.py

**Comment by deep-diver** [comment]
Tell me which model you want to try?

**Comment by honeybansal9** [comment]
It is custom gpt trained

**Comment by deep-diver** [comment]
Have you tried out BYOM feature? Which model from `transformers` is your model based on?

**Comment by deep-diver** [comment]
I see @honeybansal9. Can you show me how you have changed the base code?

**Comment by honeybansal9** [comment]
Sure the base model is pythia-gpt-neox one.
Attaching the screenshot
<img width="1512" alt="Screenshot 2023-06-22 at 6 08 34 PM" src="https://github.com/deep-diver/LLM-Pref-Mark-UI/assets/31152016/33ea563d-89b3-46f9-ab8f-ffbdb1840cc0">
I have changed the model param with the model path where it is stored.

**Comment by deep-diver** [comment]
Your model is not a Seq2SeqLM obviously, so You would need AutoModelForCausalLM.
Then, I am not sure what "/data/......" means. Is it the dataset? or the fine-tuned model?

if it is the path where the fine-tuned model exists, you want to do as follows:
```python
from transformers import AutoModelForCausalLM

model_id = "/data/..."

if torch_device == "cuda":
    # set load_in_8bit if you want it
    model = AutoModelForCausalLM.from_pretrained(model_id, device_map="auto")
else:
    model = ....
```

then you want to do the similar thing for `AutoTokenizer` and `GenerationConfig`. If you are not new to `transformers`, you know what I mean. Otherwise, read and study about it a bit.

**Comment by honeybansal9** [comment]
Thankyou so much for the help it is working fine now :)
